secrets_manager_secret_arn = "arn:aws:secretsmanager:region:your-account-id:secret:secret-name"
rds_secret_arn = "arn:aws:secretsmanager:us-east-1:your-account-id:secret:my-rds-secret"
s3_bucket_name             = "my-s3-bucket"
sns_topic_name             = "my-sns-topic"
sqs_queue_name             = "my-sqs-queue"
aws_account_id             = "your-account-id"
aws_region = "us-east-1"
